sudo: required

dist: xenial

services:
  - docker

branches:
  exclude:
    - /^ADR-.*$/ 

jobs:
  include:
    - stage: build
      name: "Build Docker Image"
      script:
        - TAG=`grep SNAPSHOT pom.xml | sed 's|[<,>,/,version ]||g'`
        - echo $TAG
        - sed -i -- "s/VER/${TAG}/g" app/index.html
        - docker build -t vaibhavthakur/nginx-demo:$TAG .
        - echo "$DOCKERPASS" | docker login -u vaibhavthakur --password-stdin
        - docker push vaibhavthakur/nginx-demo:$TAG
        - sed -i -- "s/TAG/${TAG}/g" demo-nginx.yaml
        - cat demo-nginx.yaml
        
        
addons:
  artifacts: true
  paths:
    - ./demo-nginx.yaml
  debug: true
    
